FROM golang:1.24.3-alpine3.21

RUN apk update && apk upgrade
RUN apk add --no-cache  \
    build-base  \
    make

RUN adduser -D -s /bin/bash go && mkdir -p /go && chown go:go /go

USER go

RUN go install github.com/air-verse/air@latest

WORKDIR /app

CMD ["sleep", "infinity"]
